parameters:
    pixxio.pixxio.attribute_type.class: Pixxio\PixxioConnector\AttributeType\PixxioType

services:
    pixxio.pixxio.attribute_type.image:
        class: "%pixxio.pixxio.attribute_type.class%"
        arguments:
            - text
        tags:
            - {name: pim_catalog.attribute_type, alias: pixxio_image, entity: "%pim_catalog.entity.product.class%"}
