services:
    pim_catalog.comparator.attribute.pixxio_image:
        class: '%pim_catalog.comparator.attribute.scalar.class%'
        arguments:
            - ['pixxio_image']
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -128 }
