services:
    flagbit.pixxio.comparator.attribute.pixxio_image:
        class: '%pim_catalog.comparator.attribute.scalar.class%'
        arguments:
            - [ !php/const \Flagbit\PixxioConnector\AttributeType\PixxioType::PIXXIO_IMAGE ]
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -128 }
