services:
    flagbit_pixxio.factory.value.field:
        class: Flagbit\PixxioConnector\Component\Product\Factory\Value\PixxioValueFactory
        tags: ['akeneo.pim.enrichment.factory.product_value']
