services:
    pixxio.pixxio.factory.value.field:
        class: Pixxio\PixxioConnector\Component\Product\Factory\Value\PixxioValueFactory
        tags: ['akeneo.pim.enrichment.factory.product_value']
