parameters:
    pim_catalog.query.elasticsearch.filter.pixxio.class: Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\TextFilter

services:
    pim_catalog.query.elasticsearch.filter.text:
        class: '%pim_catalog.query.elasticsearch.filter.pixxio.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute_filter'
            - [ 'pixxio_image' ]
            - ['STARTS WITH', 'CONTAINS', 'DOES NOT CONTAIN', '=', 'EMPTY', 'NOT EMPTY', '!=']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.product_filter', priority: 30 }
            - { name: 'pim_catalog.elasticsearch.query.product_model_filter', priority: 30 }
            - { name: 'pim_catalog.elasticsearch.query.product_and_product_model_filter', priority: 30 }
